[window]
size = [325.00, 375.00]
resizable = false
position = [0.0, 0.0]
corner_radius = 24
lock_in_center = true

[window.drop_shadow]
offset = [1, 1]
blur = 4
spread = 2

[window.drop_shadow.color]
hex = "#151615"
opacity = 45

[theme.background]
hex = "#161616"
opacity = 100

[theme.heading]
hex = "#FEFEFE"
opacity = 100

[dot_grid]
column_count = 21

[dot_grid.color_past]
hex = "#525152"
opacity = 100

[dot_grid.color_future]
hex = "#D7D7D7"
opacity = 100

[dot_grid.color_today]
hex = "#FEFEFE"
opacity = 100

[dot_grid.color_today_glow]
hex = "#F0F0F0"